### ISSUE TITLE
getting text files with .bin extension instead of binary octet-stream?

### ISSUE THREAD

**Issue by siddikui** [dondon2475848/make_datafiles_for_pgn#1]
Hello! Thanks for sharing the repo. When I run the code, the tokenization part works fine. But the generated .bin files are plain text files and are empty. What could possibly be wrong?

**Comment by pruthvishetty** [comment]
Same issue here. The files in the `finished_files` dir are of 0 bytes size.

**Comment by siddikui** [comment]
Seems like this line: story_fnames = [name for name in os.listdir(tokenized_stories_dir) if os.path.isfile(tokenized_stories_dir+'\\'+name) ] in the write_to_bin function was causing the trouble. Use: story_fnames = [name for name in os.listdir(tokenized_stories_dir)] instead.

**Comment by pruthvishetty** [comment]
@siddikui Thanks! That solves the problem.

**Comment by Shujian2015** [comment]
Thanks siddikui. Seems the author use Windows system where '\\' is not valid for other OS.

**Comment by dondon2475848** [comment]
@Shujian2015 Yes,I use windows 10.
All Environment can find from README.md
Other OS need edit some code like @siddikui doing.
@siddikui Thank you for your prompt reply
